# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: base
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: drag_drop_in_js
    depends_on:
      - db
    volumes:
      - ./app/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true